[logger]
level = "INFO"
path = "./logs/calendar.log"

[storage]
driver = "postgres" #[memory|postgres]

[db]
host = "localhost"
port = 5432
name = "otus-db"
username = "postgres"
password = "postgres"
 