[logger]
level = "DEBUG"
path = "./logs/scheduler.log"

[storage]
driver = "postgres"              #[memory|postgres]
migrations_path = "./migrations"

[db]
host = "localhost"
port = 5432
name = "otus-db"
username = "postgres"
password = "postgres"

[scheduler]
runFrequencyInterval = "5s"      # Run scheduler service every 5 seconds
timeForRemoveOldEvents = "8760h" # Remove old events that older than 1 year

[rmq]
uri = "amqp://guest:guest@localhost:5672/"
consumerTag = "test"
maxElapsedTime = "1m"
initialInterval = "1s"
multiplier = 2
maxInterval = "15s"

[rmq.exchange]
name = "events"
type = "fanout"
queueName = "notifications"
bindingKey = ""
