[logger]
level = "INFO"
path = "./logs/scheduler.log"

[storage]
driver = "postgres" #[memory|postgres]

[db]
host = "localhost"
port = 5432
name = "otus-db"
username = "postgres"
password = "postgres"

[rmq]
uri = "amqp://guest:guest@localhost:5672/"
consumerTag = "test"
maxElapsedTime = "1m"
initialInterval = "1s"
multiplier = 2
maxInterval = "15s"

[rmq.exchange]
    name = "events"
    type = "fanout"
    queueName = "notifications"
    bindingKey = ""